<?php

namespace App\Services;

/**
 * Lightweight RouterOS API Client
 */
class MikrotikService
{
    private $client;
    private $host;
    private $user;
    private $pass;
    private $port;

    public function __construct()
    {
        $this->host = env('MIKROTIK_HOST');
        $this->user = env('MIKROTIK_USERNAME');
        $this->pass = env('MIKROTIK_PASSWORD');
        $this->port = env('MIKROTIK_PORT', 8728);
    }

    public function connect()
    {
        // Use cache to prevent blocking on every request if router is offline
        return \Illuminate\Support\Facades\Cache::remember('mikrotik_connected', 30, function () {
            $this->client = new \App\Services\RouterosAPI();
            $this->client->debug = false;
            $connected = $this->client->connect($this->host, $this->user, $this->pass, $this->port);
            if ($connected) {
                $this->client->disconnect();
                return true;
            }
            return false;
        });
    }

    private function connectInternal()
    {
        $this->client = new \App\Services\RouterosAPI();
        $this->client->debug = false;
        return $this->client->connect($this->host, $this->user, $this->pass, $this->port);
    }

    public function createProfile($data)
    {
        if (!$this->connectInternal()) return false;

        // Mikrotik format: name, rate-limit (rx/tx), session-timeout, shared-users
        $rateLimit = ($data['upload_limit'] ?: '0') . '/' . ($data['download_limit'] ?: '0');
        
        $params = [
            'name' => $data['name'],
            'rate-limit' => $rateLimit,
            'shared-users' => (string)$data['shared_users'],
            'status-autorefresh' => '1m',
        ];

        // If duration is provided (e.g. 7h), set session-timeout
        if ($data['duration']) {
            $params['session-timeout'] = $data['duration'];
        }

        $result = $this->client->comm('/ip/hotspot/user/profile/add', $params);
        $this->client->disconnect();

        return $result;
    }
    
    public function updateProfile($oldName, $data)
    {
        if (!$this->connectInternal()) return false;
        
        // Find ID first
        $profiles = $this->client->comm('/ip/hotspot/user/profile/print', [
            '.proplist' => '.id',
            '?name' => $oldName
        ]);
        
        if (empty($profiles)) {
            $this->client->disconnect();
            return false;
        }

        $rateLimit = ($data['upload_limit'] ?: '0') . '/' . ($data['download_limit'] ?: '0');
        
        $params = [
            '.id' => $profiles[0]['.id'],
            'name' => $data['name'],
            'rate-limit' => $rateLimit,
            'shared-users' => (string)$data['shared_users'],
        ];

        if ($data['duration']) {
            $params['session-timeout'] = $data['duration'];
        } else {
            $params['session-timeout'] = '00:00:00'; // No limit
        }

        $result = $this->client->comm('/ip/hotspot/user/profile/set', $params);
        $this->client->disconnect();

        return $result;
    }

    public function deleteProfile($name)
    {
        if (!$this->connectInternal()) return false;
        
        // Find ID first
        $profiles = $this->client->comm('/ip/hotspot/user/profile/print', [
            '.proplist' => '.id',
            '?name' => $name
        ]);
        
        if (!empty($profiles)) {
            $this->client->comm('/ip/hotspot/user/profile/remove', [
                '.id' => $profiles[0]['.id']
            ]);
        }
        
        $this->client->disconnect();
    }

    public function createUser($data)
    {
        if (!$this->connectInternal()) return false;

        $params = [
            'name' => $data['username'], // Voucher Code
            'password' => $data['password'] ?? '',
            'profile' => $data['profile'], // Master Voucher Name
            'comment' => $data['comment'] ?? 'Auto-generated by NDBilling',
            'limit-uptime' => $data['limit_uptime'] ?? '0'
        ];

        $result = $this->client->comm('/ip/hotspot/user/add', $params);
        $this->client->disconnect();

        return $result;
    }

    public function deleteUser($username)
    {
        if (!$this->connectInternal()) return false;
        
        $users = $this->client->comm('/ip/hotspot/user/print', [
            '.proplist' => '.id',
            '?name' => $username
        ]);
        
        if (!empty($users)) {
            $this->client->comm('/ip/hotspot/user/remove', [
                '.id' => $users[0]['.id']
            ]);
        }
        
        $this->client->disconnect();
    }

    public function setUserStatus($username, $enabled)
    {
        if (!$this->connectInternal()) return false;
        
        $users = $this->client->comm('/ip/hotspot/user/print', [
            '.proplist' => '.id',
            '?name' => $username
        ]);
        
        if (!empty($users)) {
            $this->client->comm('/ip/hotspot/user/set', [
                '.id' => $users[0]['.id'],
                'disabled' => $enabled ? 'no' : 'yes'
            ]);
        }
        
        $this->client->disconnect();
    }

    public function clearUserActiveSessions($username)
    {
        if (!$this->connectInternal()) return false;
        
        $sessions = $this->client->comm('/ip/hotspot/active/print', [
            '.proplist' => '.id',
            '?user' => $username
        ]);
        
        foreach ($sessions as $session) {
            $this->client->comm('/ip/hotspot/active/remove', [
                '.id' => $session['.id']
            ]);
        }
        
        $this->client->disconnect();
    }

    public function clearUserCookies($username)
    {
        if (!$this->connectInternal()) return false;
        
        $cookies = $this->client->comm('/ip/hotspot/cookie/print', [
            '.proplist' => '.id',
            '?user' => $username
        ]);
        
        foreach ($cookies as $cookie) {
            $this->client->comm('/ip/hotspot/cookie/remove', [
                '.id' => $cookie['.id']
            ]);
        }
        
        $this->client->disconnect();
    }

    public function checkUserExists($username)
    {
        // Fail fast if we know router is offline
        if (!$this->connect()) return false;
        
        // Re-connect for actual check (since previous connect() was cached and disconnected)
        if (!$this->connectInternal()) return false;
        
        $users = $this->client->comm('/ip/hotspot/user/print', [
            '.proplist' => 'name',
            '?name' => $username
        ]);
        
        $this->client->disconnect();
        return !empty($users);
    }

    public function getActiveUsers()
    {
        if (!$this->connect()) return [];
        if (!$this->connectInternal()) return [];
        
        $active = $this->client->comm('/ip/hotspot/active/print');
        
        $this->client->disconnect();
        return is_array($active) ? $active : [];
    }

    public function removeHotspotUser($username)
    {
        return $this->deleteUser($username);
    }
}

/**
 * Basic RouterOS API Class
 */
class RouterosAPI {
    var $debug = false;
    var $connected = false;
    var $port = 8728;
    var $timeout = 1; // 1 second timeout for fast failure
    var $attempts = 1; // Only 1 attempt to prevent hanging
    var $delay = 0;
    var $socket;
    var $error_no;
    var $error_str;

    function connect($host, $user, $pass, $port = 8728) {
        if (!$host) return false;
        
        $this->socket = @fsockopen($host, $port, $this->error_no, $this->error_str, $this->timeout);
        if ($this->socket) {
            socket_set_timeout($this->socket, $this->timeout);
            if ($this->login($user, $pass)) {
                $this->connected = true;
                return true;
            }
            fclose($this->socket);
        }
        return false;
    }

    function disconnect() {
        if ($this->socket) fclose($this->socket);
        $this->connected = false;
    }

    function login($user, $pass) {
        $this->write('/login');
        $res = $this->read(false);
        if (isset($res[0]) && $res[0] == '!done') {
            if (isset($res[1])) {
                $challange = substr($res[1], 9);
                $md5 = md5(chr(0) . $pass . pack('H*', $challange));
                $this->write('/login', false);
                $this->write('=name=' . $user, false);
                $this->write('=response=00' . $md5);
                $res = $this->read(false);
                if ($res[0] == '!done') return true;
            }
        }
        return false;
    }

    function comm($com, $args = array()) {
        if (!$this->connected) return false;
        $this->write($com, false);
        foreach ($args as $key => $value) {
            $this->write('=' . $key . '=' . $value, false);
        }
        $this->write($com, true);
        return $this->read();
    }

    function write($command, $param2 = true) {
        if ($command) {
            $data = explode("\n", $command);
            foreach ($data as $com) {
                $com = trim($com);
                $this->encode_length(strlen($com));
                fwrite($this->socket, $com);
            }
            if ($param2) fwrite($this->socket, chr(0));
            return true;
        }
        return false;
    }

    function read($parse = true) {
        $res = array();
        while (true) {
            $length = $this->decode_length();
            if ($length > 0) {
                $byte_read = 0;
                $line = '';
                while ($byte_read < $length) {
                    $temp = fread($this->socket, $length - $byte_read);
                    $byte_read += strlen($temp);
                    $line .= $temp;
                }
                $res[] = $line;
            } elseif ($length == 0) {
                break;
            }
        }
        if ($parse) {
            $parsed = array();
            $current = null;
            foreach ($res as $line) {
                if ($line == '!re' || $line == '!trap' || $line == '!done') {
                    $current = array('type' => $line);
                    $parsed[] = &$current;
                } elseif (substr($line, 0, 1) == '=') {
                    $parts = explode('=', $line, 3);
                    $current[$parts[1]] = isset($parts[2]) ? $parts[2] : '';
                }
            }
            return $parsed;
        }
        return $res;
    }

    function encode_length($length) {
        if ($length < 0x80) {
            fwrite($this->socket, chr($length));
        } elseif ($length < 0x4000) {
            fwrite($this->socket, chr(($length >> 8) | 0x80) . chr($length & 0xff));
        } elseif ($length < 0x200000) {
            fwrite($this->socket, chr(($length >> 16) | 0xc0) . chr(($length >> 8) & 0xff) . chr($length & 0xff));
        } elseif ($length < 0x10000000) {
            fwrite($this->socket, chr(($length >> 24) | 0xe0) . chr(($length >> 16) & 0xff) . chr(($length >> 8) & 0xff) . chr($length & 0xff));
        } else {
            fwrite($this->socket, chr(0xf0) . chr(($length >> 24) & 0xff) . chr(($length >> 16) & 0xff) . chr(($length >> 8) & 0xff) . chr($length & 0xff));
        }
    }

    function decode_length() {
        $byte = ord(fread($this->socket, 1));
        if (($byte & 0x80) == 0x00) {
            return $byte;
        } elseif (($byte & 0xc0) == 0x80) {
            return (($byte & 0x3f) << 8) + ord(fread($this->socket, 1));
        } elseif (($byte & 0xe0) == 0xc0) {
            return (($byte & 0x1f) << 16) + (ord(fread($this->socket, 1)) << 8) + ord(fread($this->socket, 1));
        } elseif (($byte & 0xf0) == 0xe0) {
            return (($byte & 0x0f) << 24) + (ord(fread($this->socket, 1)) << 16) + (ord(fread($this->socket, 1)) << 8) + ord(fread($this->socket, 1));
        } elseif (($byte & 0xf8) == 0xf0) {
            return (ord(fread($this->socket, 1)) << 24) + (ord(fread($this->socket, 1)) << 16) + (ord(fread($this->socket, 1)) << 8) + ord(fread($this->socket, 1));
        }
        return 0;
    }
}
